apiVersion: apps/v1
kind: Deployment
metadata:
  name: glotixz-frontend
  labels:
    type: stage-depl
    svcname: frontend-svc
    version: v1
    deployment: bluedeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glotixz-frontend
      version: v1
  template:
    metadata:
      labels:
        app: glotixz-frontend
        version: v1
    spec:
      serviceAccountName: glotixz-frontend
      containers:
        - name: glotixz-frontend
          image: typrone1/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: BASEURL
              value: a482a497403784e66a2a70a77561dd1c-1139531466.ap-southeast-1.elb.amazonaws.com
            - name: NEXT_PUBLIC_BASEURL
              value: a482a497403784e66a2a70a77561dd1c-1139531466.ap-southeast-1.elb.amazonaws.com
            - name: NEXT_PUBLIC_STRIPE_KEY
              value: 'pk_test_51IWeSrSGJ6cJaAGg6Be4Ty2WnNfEwASS11HO2syVLoAJGesykRVi9K19rzTjTBUBySdezIcFwHzDLyp2oX4BIssn007PlgW6Za'  
            