apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
  labels:
    type: dev-depl
    svcname: frontend-svc
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: typrone1/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: BASEURL
              value: 192.168.49.2:32684
            - name: NEXT_PUBLIC_BASEURL
              value: localhost
            - name: NEXT_PUBLIC_STRIPE_KEY
              value: 'pk_test_51IWeSrSGJ6cJaAGg6Be4Ty2WnNfEwASS11HO2syVLoAJGesykRVi9K19rzTjTBUBySdezIcFwHzDLyp2oX4BIssn007PlgW6Za'  
            
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-srv
  labels:
    app: frontend
    service: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http-frontend
      protocol: TCP
      port: 3001
      targetPort: 3001
  # type: LoadBalancer
  type: ClusterIP

